rootProject.name = "Halachic Times"
include("GeoNames")
include("zmanim")
include("android-lib:lib")
include("common")
include("locations")
include("compass-lib")
include("app")
include("compass")
include("compass-bahai")
include("compass-jewish")
